-- 易搭 v0.1：Supabase 数据库与私有图片存储
-- 在 Supabase Dashboard -> SQL Editor 中一次性运行。

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '晚晚',
  preferred_styles jsonb not null default '["简约通勤","清爽休闲"]'::jsonb,
  last_scene text,
  weather_city text,
  weather_latitude double precision,
  weather_longitude double precision,
  body_height integer,
  body_weight integer,
  body_shape text,
  model_presentation text,
  full_body_image_key text,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.garments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  catalog_key text,
  name text not null,
  category text not null,
  color text not null,
  color_name text not null,
  meta text not null default '',
  warmth integer not null default 2,
  style_tags jsonb not null default '[]'::jsonb,
  scene_tags jsonb not null default '[]'::jsonb,
  weather_tags jsonb not null default '[]'::jsonb,
  is_virtual boolean not null default true,
  image_key text,
  processed_image_key text,
  recognition_status text not null default 'manual',
  recognition_confidence integer not null default 0,
  recognition_provider text,
  recognized_at timestamptz,
  dirty_until timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists idx_garments_user_catalog
  on public.garments(user_id, catalog_key);

create table if not exists public.outfit_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  outfit_key text not null,
  action text not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active_request text,
  constraints jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.recognition_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null,
  count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create table if not exists public.visualization_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  usage_date date not null,
  count integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create index if not exists idx_feedback_user_created
  on public.outfit_feedback(user_id, created_at desc);
create index if not exists idx_chat_messages_user_created
  on public.chat_messages(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.garments enable row level security;
alter table public.outfit_feedback enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.recognition_usage enable row level security;
alter table public.visualization_usage enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'profiles', 'garments', 'outfit_feedback', 'chat_sessions',
    'chat_messages', 'recognition_usage', 'visualization_usage'
  ] loop
    execute format(
      'create policy "users_manage_own_rows" on public.%I for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())',
      table_name
    );
  end loop;
end $$;

grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.garments to authenticated;
grant select, insert, update, delete on public.outfit_feedback to authenticated;
grant select, insert, update, delete on public.chat_sessions to authenticated;
grant select, insert, update, delete on public.chat_messages to authenticated;
grant select, insert, update, delete on public.recognition_usage to authenticated;
grant select, insert, update, delete on public.visualization_usage to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'garment-images',
  'garment-images',
  false,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "users_read_own_garment_images"
  on storage.objects for select to authenticated
  using (bucket_id = 'garment-images' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users_insert_own_garment_images"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'garment-images' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users_update_own_garment_images"
  on storage.objects for update to authenticated
  using (bucket_id = 'garment-images' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'garment-images' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users_delete_own_garment_images"
  on storage.objects for delete to authenticated
  using (bucket_id = 'garment-images' and (storage.foldername(name))[1] = auth.uid()::text);
